# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source ‘https://github.com/CocoaPods/Specs.git’

target 'EasyRTC' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyRTC
  pod 'Bugly'
  pod 'Masonry'
  pod 'MJRefresh'
  pod 'AFNetworking'
  pod 'MBProgressHUD'
  pod 'IQKeyboardManager'
  pod 'RTRootNavigationController'
  pod 'YYKit'

  #    pod 'ReactiveCocoa', '~> 2.5'
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'

end
